### PR TITLE
Stable tests

### LINKED ISSUE #98: some tests fails each run, but each time different test
Hello Zack,

if I run tests, some tests fail. But each time different tests fail without I change anything.

Is it the same for you?

Regards,
Richard

### PR DESCRIPTION
**Pull request by r1mar**
Hello Zack,

I abstracted the database. This makes the tests run deterministically. closes #98

Regards,
Richard

### CODE REVIEW

**Comment by zackyang000** [comment]
wow, great job, I will check it ASAP.

**Comment by r1mar** [comment]
Hello Zack,

I have implemented the generation of metadata. However, only for features that the service can currently provide. Only for unbound functions and bound actions.

The metadata can be queried both in Json and in XML format. You can use both the "accept" header and the "format" parameter to switch. The interaction should be protocol-compliant.

Unfortunately, I slipped an intermediate commit. Sorry.

Greeting,
Richard

**Comment by zackyang000** [comment]
> r1mar

Hi r1mar, 

Yeah, there are a lot of changes here, it's merged, I will release a beta npm package for this commit, thanks for the PR.

I'd love to know when you're using metadata, as I haven't been able to find a good case before. I would appreciate it if you could tell me.

**Comment by r1mar** [comment]
Hello Zack,

I don't think you need to deploy the current state in NPM. I'm still okay. The repository isn't at the level I need yet. Therefore, I will create more pull requests. Next I wanted to update the dependencies.

From a formal point of view, support for metadata generation is one of the minimum requirements for an OData implementation, see [OData40MinimalConformanceLevel](http://docs.oasis-open.org/odata/odata/v4.01/odata-v4.01-part1-protocol.html#sec_OData40MinimalConformanceLevel) I want to build an application using the UI5 framework [oPENui5](https://github.com/SAP/openui5). The framework only works with a service that generates metadata.

Greeting,
Richard

**Pull request merged**
